spring:
  datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloudTest
        username: root
        password: root
  
  jpa:
    hibernate:
        ddl-auto: update
        
security:
  basic:
    enabled: false    