spring:
    application:
        name: employee eureka client
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/employee
        username: root
        password: root
    jpa:
      hibernate:
        ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  basic:
    enabled: false
      