spring:
    application:
        name: employee
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/employee
        username: root
        password: root
    jpa:
      hibernate:
        ddl-auto: update
